name: NuGet Generation

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v3
        with:
          source-url: https://nuget.pkg.github.com/andrewgoacher/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOKEN}}    
          
      - name: Build solution and generate NuGet package
        run: dotnet pack -c Release 

      - name: Push generated package to GitHub registry
        run: dotnet nuget push "./src/nvm/nupkg/*.nupkg" --api-key  ${{secrets.NUGET_TOKEN}} --skip-duplicate --no-symbols 
